# The difficulty of the end game
# Affects how many options exist, with there
# being over 900 more options on hard mode
# Valid values: 0, 3, 4
Wikipedia List Level: 3

# The maximum number of guesses the player can make
# before the game ends
Max Guesses: 5

Port: 3465
Scrape Delay: 0.1 # Delay between scraping pages in seconds
Scrape Data Location: "./data" # Location of scraped data
Database Location: "./metrics.db"

Version: "v0.0.1"
Server Debug: False

# A list of additional people to add to the game
# on top of the vital articles
# Must be exact titles of Wikipedia articles
Additional People:
  - "John F. Kennedy"
  - "Humphrey Bogart"
  - "Jackie Chan"
  - "Tom Hanks"
  - "Marilyn Monroe"
  - "Monty Python"
  - "Bill Cosby"
  - "Harry Houdini"
  - "Oprah Winfrey"
  - "El Greco"
  - "Salvador Dalí"
  - "Dr. Seuss"
  - "Ovid"
  - "Du Fu"
  - "Nostradamus"
  - "Maya Angelou"
  - "Isaac Asimov"
  - "Emily Dickinson"
  - "Langston Hughes"
  - "H. P. Lovecraft"
  - "Edgar Allan Poe"
  - "Mark Twain"
  - "Kurt Vonnegut"
  - "Anton Chekhov"
  - "Anne Frank"
  - "Johann Wolfgang von Goethe"
  - "Brothers Grimm"
  - "James Joyce"
  - "Mary Shelley"
  - "J. R. R. Tolkien"
  - "Frédéric Chopin"
  - "Claude Debussy"
  - "Frank Sinatra"
  - "Pink Floyd"
  - "Alfred Hitchcock"
  - "Neil Armstrong"
  - "Diogenes"
  - "David Hume"
  - "Thomas Paine"
  - "Noam Chomsky"
  - "Noah Webster"
  - "Grigori Rasputin"
  - "Pope Francis"
  - "Pope Benedict XVI"
  - "Zoroaster"
  - "Cao Cao"
  - "Attila"
  - "Tecumseh"
  - "Benjamin Franklin"
  - "John Adams"
  - "Thomas Jefferson"
  - "Alexander Hamilton"
  - "Ivan the Terrible"
  - "William the Silent"
  - "Catherine de' Medici"
  - "Fidel Castro"
  - "Dwight D. Eisenhower"
  - "Richard Nixon"
  - "Ronald Reagan"
  - "Barack Obama"
  - "Mark Antony"
  - "Hannibal"
  - "Sun Tzu"
  - "Ulysses S. Grant"
  - "Blackbeard"
  - "Spartacus"
  - "Malcolm X"
  - "Martin Luther King Jr."
  - "Rosa Parks"
  - "Harriet Tubman"
  - "Niels Bohr"
  - "Enrico Fermi"
  - "Samuel Morse"
  - "Wright brothers"
  - "Ada Lovelace"
  - "Edsger W. Dijkstra"
  - "Linus Torvalds"
  - "Usain Bolt"
  - "Garry Kasparov"
  - "Bobby Fischer"
  - "Tiger Woods"
  - "Bruce Lee"
  - "Michael Jordan"
  - "Babe Ruth"
